export default{
     SAVE_ORDER_SUCCESS: 'SAVE_ORDER_SUCCESS',
     SAVE_ORDER_FAILED: 'SAVE_ORDER_FAILED',
     DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
     DELETE_ORDER_FAILED: 'DELETE_ORDER_FAILED',
     FETCH_ORDERS_REQUEST: 'FETCH_ORDERS_REQUEST',
     FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
     FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL'
}
