export default{
     SAVE_PRODUCT_SUCCESS: 'SAVE_PRODUCT_SUCCESS',
     SAVE_PRODUCT_FAILED: 'SAVE_PRODUCT_FAILED',
     DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
     DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',
     FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
     FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
     FETCH_PRODUCTS_FAIL: 'FETCH_PRODUCTS_FAIL',
     UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
     UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
}
